baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

description: Foursite.me

# twitter: 
# medium: 
# linkedin: 

# collections:
#   portfolio:

# # Other
# markdown: kramdown

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true